/* Generated by Yosys 0.68+71 (git sha1 dbe5b7c03-dirty, Release, GNU /usr/bin/x86_64-w64-mingw32-g++ 15.2.1) */

module advanced_memory_controller(clk, rst, write_en, read_en, addr, write_data, read_data, read_valid, busy);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input write_en;
  wire write_en;
  input read_en;
  wire read_en;
  input [5:0] addr;
  wire [5:0] addr;
  input [31:0] write_data;
  wire [31:0] write_data;
  output [31:0] read_data;
  reg [31:0] read_data;
  output read_valid;
  reg read_valid;
  output busy;
  reg busy;
  wire [5:0] _00_;
  wire [31:0] _01_;
  wire [31:0] _02_;
  wire _03_;
  wire [31:0] _04_;
  wire _05_;
  wire [5:0] _06_;
  wire [31:0] _07_;
  wire [31:0] _08_;
  wire [31:0] _09_;
  wire _10_;
  wire _11_;
  wire [31:0] _12_;
  reg [31:0] memory [63:0];
  always @(posedge clk) begin
    if (_02_[0])
      memory[_00_] <= _01_;
  end
  assign _09_ = memory[addr];
  always @(posedge clk)
    read_data <= _04_;
  always @(posedge clk)
    read_valid <= _05_;
  always @(posedge clk)
    busy <= _03_;
  assign _07_ = write_en ? write_data : 32'hxxxxxxxx;
  assign _06_ = write_en ? addr : 6'hxx;
  assign _08_[0] = write_en ? 1'h1 : 1'h0;
  assign _10_ = read_en ? 1'h1 : _08_[0];
  assign _03_ = rst ? 1'h0 : _10_;
  assign _11_ = read_en ? 1'h1 : 1'h0;
  assign _05_ = rst ? 1'h0 : _11_;
  assign _02_[0] = rst ? 1'h0 : _08_[0];
  assign _01_ = rst ? 32'hxxxxxxxx : _07_;
  assign _00_ = rst ? 6'hxx : _06_;
  assign _12_ = read_en ? _09_ : read_data;
  assign _04_ = rst ? 32'd0 : _12_;
  assign _08_[31:1] = { _08_[0], _08_[0], _08_[0], _08_[0], _08_[0], _08_[0], _08_[0], _08_[0], _08_[0], _08_[0], _08_[0], _08_[0], _08_[0], _08_[0], _08_[0], _08_[0], _08_[0], _08_[0], _08_[0], _08_[0], _08_[0], _08_[0], _08_[0], _08_[0], _08_[0], _08_[0], _08_[0], _08_[0], _08_[0], _08_[0], _08_[0] };
  assign _02_[31:1] = { _02_[0], _02_[0], _02_[0], _02_[0], _02_[0], _02_[0], _02_[0], _02_[0], _02_[0], _02_[0], _02_[0], _02_[0], _02_[0], _02_[0], _02_[0], _02_[0], _02_[0], _02_[0], _02_[0], _02_[0], _02_[0], _02_[0], _02_[0], _02_[0], _02_[0], _02_[0], _02_[0], _02_[0], _02_[0], _02_[0], _02_[0] };
endmodule
